export interface Registration {
    studentId: any;
    hostelId: any;
    studentName: string;
    age: number;
    dob: string;
    bloodGroup: string;
    gender: string;
    motherTongue: string;
    mobileNo: string;
    altMobNo: string;
    religion: string;
    caste: string;
    subCaste: string;
    studentFilename: string;
    instituteName: string;
    course: string;
    medium: string;
    classId: string;
    courseTitle: string;
    lastStudiedInstituteName: string;
    lastStudiedInstituteAddress: string;
    distanceFromHostelToHome: any;
    distanceFromHostelToInstitue: any;
    disabilityType: any;
    address1: string;
    address2: string;
    landmark: string;
    distrctCode: number;
    talukCode: number;
    village: string;
    pincode: number;
    aadharNo: string;
    rationCardrNo: string;
    emisno: any;
    talukApproval: any;
    districtApproval: any;
    //bank
    bankId: any;
    bankName: string;
    bankAccNo: string;
    ifscCode: string;
    branchName: string;
    //parent's info
    parentId: number;
    fatherName: string;
    fatherOccupation: string;
    fatherMoileNo: string;
    fatherQualification: string;
    fatherYIncome: string;
    motherName: string;
    motherOccupation: string;
    motherMoileNo: string;
    motherQualification: string;
    motherYIncome: string;
    guardianName: string;
    guardianOccupation: string;
    guardianMobileNo: string;
    guardianQualification: string;
    totalYIncome: string;
    documentId: number,
    incomeCertificateFilename: string;
    tcFilename: string;
    bankPassbookFilename: string;
    declarationFilename: string;

}